export const START_ANALYSIS = 'START_ANALYSIS';
export const FETCH_DATA = 'FETCH_DATA';
export const LATEST_DATA = 'LATEST_DATA';
export const PARAMETER_ONE_DATA = 'PARAMETER_ONE_DATA';
export const PARAMETER_TWO_DATA = 'PARAMETER_TWO_DATA';
export const PARAMETER_THREE_DATA = 'PARAMETER_THREE_DATA';
export const GET_TIME = 'GET_TIME';
